### ISSUE TITLE
Use of custom pages - how to?

### ISSUE THREAD

**Issue by SAOPP** [acouvreur/traefik-ondemand-plugin#16]
Hi!

Guys, what the command I need to add in plugin container for use custom pages? 

I don't quite understand, based on the description there is only a block, can I use labels in the plugin container, if so which ones?

**Comment by acouvreur** [comment]
I used the sources from `examples/docker_swarm` and tweaked it just to add a custom loading page :

```diff
version: "3.9"

services:
  traefik:
    image: traefik
    command:
      - --api=true
      - --api.insecure=true
      - --pilot.token=$TRAEFIK_PILOT_TOKEN
      - --experimental.plugins.traefik-ondemand-plugin.moduleName=github.com/acouvreur/traefik-ondemand-plugin
-     - --experimental.plugins.traefik-ondemand-plugin.version=v1.0.1 # Custom loading pages are in 1.1.0
+     - --experimental.plugins.traefik-ondemand-plugin.version=v1.1.0
      - --providers.docker=true
      - --providers.docker.swarmmode=true
      - --providers.file.filename=/etc/traefik/dynamic-config.yml
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
+     - './mycustompages:/etc/traefik/plugins/traefik-ondemand-plugin/custompages'
    
  ondemand:
    image: ghcr.io/acouvreur/traefik-ondemand-service:1
    command:
      - --swarmMode=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.name=DOCKER_SWARM_nginx
        - traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.serviceUrl=http://ondemand:10000
        - traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.timeout=1m
+       - traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.loadingpage=/etc/traefik/plugins/traefik-ondemand-plugin/custompages/loading.html
+       - traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.errorpages=/etc/traefik/plugins/traefik-ondemand-plugin/custompages/error.html
        - traefik.http.services.ondemand.loadbalancer.server.port=10000

  nginx:
    image: nginx
    deploy:
      replicas: 0
      labels:
        - traefik.enable=true
        # If you do not use the swarm load balancer, traefik will evict the service from its pool
        # as soon as the service is 0/0. If you do not set that, fallback to dynamic-config.yml file usage.
        - traefik.docker.lbswarm=true
        - traefik.http.routers.nginx.middlewares=ondemand@docker
        - traefik.http.routers.nginx.rule=PathPrefix(`/nginx`)
        - traefik.http.services.nginx.loadbalancer.server.port=80
```

You need to add a volume (or swarm config) with your custom loading pages.

Your HTML page must include the following : 
```html
<meta http-equiv="refresh" content="5" />
```
Because otherwise it will not automatically reload. You can custom the refresh rate.

You have access to the following struct in loading : 
```go
type LoadingData struct {
	Name    string
	Timeout string
}
```

And in error : 
```go
type ErrorData struct {
	Name  string
	Error string
}
```

Pages are Go Templates, so feel free to do what you want with it !
Example in error.html : 

```html
<h2 class="headline" id="headline">Error loading {{ .Name }}.</h2>
```

**Comment by SAOPP** [comment]
Yeah, okay, I see your volume with custom pages, and see the labels, awesome. But, I was think some custome pages are available in the plugin or in this repos - no? I mean, I need to get them from somewhere or write it by my self? :) I'm saw a screenshoots in repo, and thinked it's something like custom pages in plugin.. :D

**Comment by acouvreur** [comment]
Default pages are available here: 
https://github.com/acouvreur/traefik-ondemand-plugin/tree/main/pkg/pages

Loading page: https://github.com/acouvreur/traefik-ondemand-plugin/blob/main/pkg/pages/loading.html
Error page: https://github.com/acouvreur/traefik-ondemand-plugin/blob/main/pkg/pages/error.html

**Comment by SAOPP** [comment]
ah, okay, sorry, I was wrong, I found it ova here: https://github.com/acouvreur/traefik-ondemand-plugin/tree/main/pkg/pages :D sorry, thanks ;) I will try.

**Comment by SAOPP** [comment]
What I do wrong?

Some from traefik container:
```
      # On demand plugin
      - --experimental.plugins.traefik-ondemand-plugin.moduleName=github.com/acouvreur/traefik-ondemand-plugin
      - --experimental.plugins.traefik-ondemand-plugin.version=v1.1.0
     
      # Ondemand plugin custom pages
      - /home/docker_storage/traefik-ondemand:/etc/traefik/plugins/traefik-ondemand-plugin/custompages

      /home/docker_storage/traefik-ondemand$ 
      -rw-r--r--  1 root root 3272 Dec 14 15:49 error.html
      -rw-r--r--  1 root root 4645 Dec 14 15:49 loading.html
```

ondemand container:
```
  traefik-ondemand:
    image: ghcr.io/acouvreur/traefik-ondemand-service:1
    container_name: traefik-ondemand
    command: 
      - --swarmMode=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 10000:10000
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.remmina-ondemand.plugin.traefik-ondemand-plugin.name=remmina
      - traefik.http.middlewares.remmina-ondemand.plugin.traefik-ondemand-plugin.serviceUrl=http://192.168.1.4:10000
      - traefik.http.middlewares.remmina-ondemand.plugin.traefik-ondemand-plugin.timeout=5m
      - traefik.http.middlewares.remmina-ondemand.plugin.traefik-ondemand-plugin.loadingpage=/etc/traefik/plugins/traefik-ondemand-plugin/custompages/loading.html
      - traefik.http.middlewares.remmina-ondemand.plugin.traefik-ondemand-plugin.errorpages=/etc/traefik/plugins/traefik-ondemand-plugin/custompages/error.html
      - traefik.http.services.traefik-ondemand.loadbalancer.server.port=10000
```
My service:      
```
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - /home/docker_storage/remmina:/config
    ports:
      - 3000:3000
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.remmina.loadbalancer.server.port=3000
      - traefik.http.routers.remmina.rule=Host(`remmina.${DOMAIN}`)
      - traefik.http.routers.remmina.entrypoints=websecure
      - traefik.http.routers.remmina.tls=true
      - traefik.http.routers.remmina.tls.certresolver=myresolver
      - traefik.http.routers.remmina.middlewares=remmina-ondemand@docker
```

After change plugin version and add volume with custom pages, and path to this pages in ondemand containr, I get 404 default page if container is down :| What I do wrong?

**Comment by acouvreur** [comment]
Your Traefik configuration may have so issues, can you print the Ondemand and Traefik logs ?

**Comment by SAOPP** [comment]
But with previous version all works fine, and in traefik dashboard any errors not found also.
Ondemand turn off container, if I run it, but no started it.

**Comment by acouvreur** [comment]
Can you give me the whole configuration ? So I can try it out ?

If you can give me some logs from Traefik, and Ondemand service it'll be helpful, thanks!

**Comment by acouvreur** [comment]
Oh, you may have the wrong template inside your error.html file !
We may need to have a better error handling I guess :thinking:

**Comment by SAOPP** [comment]
Oh, container is started

**Comment by SAOPP** [comment]
Okay I downloading templates again...

**Comment by acouvreur** [comment]
Feel free to provide feedback!

**Comment by SAOPP** [comment]
Strange, redownloaded the templates, and the same result as above. :/

**Comment by SAOPP** [comment]
I will try to set proper permissions in folder...

**Comment by SAOPP** [comment]
Ondemand logs is fine as I see:

```
Server listening on port 10000, swarmMode: false, kubernetesMode: false
time="2021-12-14T15:11:09Z" level=info msg="Scaling down remmina to 0"
time="2021-12-14T15:16:33Z" level=info msg="Scaling up remmina to 1"
time="2021-12-14T15:30:13Z" level=info msg="Scaling down remmina to 0"
time="2021-12-14T15:30:40Z" level=info msg="Scaling up remmina to 1"
time="2021-12-14T15:35:50Z" level=info msg="Scaling down remmina to 0"
time="2021-12-14T15:41:11Z" level=info msg="Scaling up remmina to 1"
time="2021-12-14T15:46:32Z" level=info msg="Scaling down remmina to 0"
time="2021-12-14T16:10:46Z" level=info msg="Scaling up remmina to 1"
time="2021-12-14T16:15:52Z" level=info msg="Scaling down remmina to 0"
time="2021-12-14T16:20:36Z" level=info msg="Scaling up remmina to 1"
time="2021-12-14T16:33:26Z" level=info msg="Scaling down remmina to 0"
time="2021-12-14T17:30:33Z" level=info msg="Scaling up remmina to 1"
time="2021-12-14T17:40:05Z" level=info msg="Scaling down remmina to 0"
time="2021-12-14T18:03:15Z" level=info msg="Scaling up remmina to 1"
time="2021-12-14T18:11:42Z" level=info msg="Scaling down remmina to 0"
time="2021-12-14T18:17:43Z" level=info msg="Scaling up remmina to 1"
time="2021-12-14T18:22:59Z" level=info msg="Scaling down remmina to 0"
time="2021-12-14T19:45:16Z" level=info msg="Scaling up remmina to 1"
```
One second, I will try to catch some ondemand outputs from traefik...

**Comment by SAOPP** [comment]
It's from remmina router:

![image](https://user-images.githubusercontent.com/5647009/146069814-5be4374a-8ccf-4284-a2ad-ef9e04d3b93f.png)

**Comment by SAOPP** [comment]
My Traefik container:

```
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # File dymanic configurations for remote services
      - --providers.file.directory=/dynamic_conf
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.traefik.address=:81
      #- --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=${EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --pilot.token=${TRAEFIK_PILOT_TOKEN}
      # On demand plugin
      - --experimental.plugins.traefik-ondemand-plugin.moduleName=github.com/acouvreur/traefik-ondemand-plugin
      - --experimental.plugins.traefik-ondemand-plugin.version=v1.1.0
    environment:
      - TZ=Europe/Kiev
    ports:
      - 80:80
      - 8246:81
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-le:/letsencrypt
      # Remote services dynamic configuration folder
      - /home/docker_storage/traefik:/dynamic_conf
      # Ondemand plugin custom pages
      - /home/docker_storage/traefik-ondemand:/etc/traefik/plugins/traefik-ondemand-plugin/custompages
    #network_mode: host
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:172.24.0.1
    networks:
      - web
    labels:
      - diun.enable=true
      # Redirect HTTP traffic to HTTPS
      - traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.redirs.entrypoints=web
      - traefik.http.routers.redirs.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      # Dashboard
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`proxy.${DOMAIN}`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.services.dashboard.loadbalancer.server.port=81
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=myresolver
      - traefik.http.routers.dashboard.middlewares=authelia@docker
```

```
Ondemand container:
  traefik-ondemand:
    image: ghcr.io/acouvreur/traefik-ondemand-service:1
    container_name: traefik-ondemand
    command: 
      - --swarmMode=false
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 10000:10000
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.remmina-ondemand.plugin.traefik-ondemand-plugin.name=remmina
      - traefik.http.middlewares.remmina-ondemand.plugin.traefik-ondemand-plugin.serviceUrl=http://192.168.1.4:10000
      - traefik.http.middlewares.remmina-ondemand.plugin.traefik-ondemand-plugin.timeout=5m
      - traefik.http.middlewares.remmina-ondemand.plugin.traefik-ondemand-plugin.loadingpage=/etc/traefik/plugins/traefik-ondemand-plugin/custompages/loading.html
      - traefik.http.middlewares.remmina-ondemand.plugin.traefik-ondemand-plugin.errorpages=/etc/traefik/plugins/traefik-ondemand-plugin/custompages/error.html
      - traefik.http.services.traefik-ondemand.loadbalancer.server.port=10000
```
