### ISSUE TITLE
Display name for the loading page

### ISSUE THREAD

**Issue by kris-g** [acouvreur/traefik-ondemand-plugin#24]
It would be nice to specify a custom display name to show on the loading page. Currently for Kubernetes you see an internal object name with format "namespace-middlewarename@kubernetescrd". I'm sure a nicer name could be achieved with the custom page feature, but a simple property in the middleware config would be nice.

**Comment by acouvreur** [comment]
I think that's a good idea.
Do you have any suggestion on how you'd configure this ?

**Comment by kris-g** [comment]
A property in the configuration alongside serviceUrl/timeout would work for me. Could call it "displayName" or "caption"?

Kubernetes example:

`
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ondemand-paperless
  namespace: traefik
spec:
  plugin:
    traefik-ondemand-plugin:
      name: deployment_3rd-party-apps_paperless_1
      displayName: Paperless
      serviceUrl: 'http://traefik-ondemand-service:10000'
      timeout: 60m
`

**Comment by acouvreur** [comment]
There is currently two strategies available : 

- The interactive strategy, with the loading screen
- The blocking strategy, which hangs the request until the service can finally respond (useful for APIs)

There may be more in the future.

I think I should try to find a better way to structure the configuration in order to not "pollute" the main configuration.

If you have any idea considering this, please feel free to share your thoughts.

But I'll probably do something like you just described in the meantime on the beta branch, and change it later.

**Comment by kris-g** [comment]
You're right, it seems over time the configuration will become polluted. The only idea I have would be nesting configuration for the two distinct modes. So you would need to throw an error if both nested configs are provided at the same time, or you could just log an info to say which one won't be used.

If you really think there might be more strategies in the future maybe they should be enabled by a strategy property instead of waitui?

Some ideas...

Kubernetes example (interactive):
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ondemand-paperless
  namespace: traefik
spec:
  plugin:
    traefik-ondemand-plugin:
      name: deployment_3rd-party-apps_paperless_1
      displayName: Paperless
      serviceUrl: 'http://traefik-ondemand-service:10000'
      timeout: 60m
      strategy: interactive # default is interactive
      interactiveConfig:
        displayName: Paperless
        loadingpage: /etc/traefik/plugins/traefik-ondemand-plugin/custompages/loading.html
        errorpage: /etc/traefik/plugins/traefik-ondemand-plugin/custompages/error.html
```

Kubernetes example (blocking):
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ondemand-paperless
  namespace: traefik
spec:
  plugin:
    traefik-ondemand-plugin:
      name: deployment_3rd-party-apps_paperless_1
      displayName: Paperless
      serviceUrl: 'http://traefik-ondemand-service:10000'
      timeout: 60m
      strategy: blocking # default is interactive
      blockingConfig:
        blockdelay: 1m
```
