### ISSUE TITLE
Feature Request: Support multiple containers

### ISSUE THREAD

**Issue by jimcortez** [acouvreur/traefik-ondemand-plugin#8]
I would love to use this on a bunch of different rarely-used containers. It seems like today in order to use the ondemand plugin, I would have to create a new ondemand container per use case. Ideally I am reducing the number of containers running at a given time, but this would actually increase.

Is this actually possible given the information at request-time?

**Comment by acouvreur** [comment]
Multiple containers are supported with one ondemand service.

You need to define multiple middleware : 

```yml
version: "3.9"

services:
  traefik:
    image: traefik
    command:
      - --api=true
      - --api.insecure=true
      - --pilot.token=$TRAEFIK_PILOT_TOKEN
      - --experimental.plugins.traefik-ondemand-plugin.moduleName=github.com/acouvreur/traefik-ondemand-plugin
      - --experimental.plugins.traefik-ondemand-plugin.version=v0.1.1
      - --providers.docker=true
      - --providers.docker.swarmmode=true
      - --providers.file.filename=/etc/traefik/dynamic-config.yml
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    
  ondemand:
    image: ghcr.io/acouvreur/traefik-ondemand-service:main
    command:
      - --swarmMode=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.ondemand-nginx1.plugin.traefik-ondemand-plugin.name=DOCKER_SWARM_nginx1
        - traefik.http.middlewares.ondemand-nginx1.plugin.traefik-ondemand-plugin.serviceUrl=http://ondemand:10000
        - traefik.http.middlewares.ondemand-nginx1.plugin.traefik-ondemand-plugin.timeout=1m
        - traefik.http.middlewares.ondemand-nginx2.plugin.traefik-ondemand-plugin.name=DOCKER_SWARM_nginx2
        - traefik.http.middlewares.ondemand-nginx2.plugin.traefik-ondemand-plugin.serviceUrl=http://ondemand:10000
        - traefik.http.middlewares.ondemand-nginx2.plugin.traefik-ondemand-plugin.timeout=1m
        - traefik.http.services.ondemand.loadbalancer.server.port=10000

  nginx1:
    image: nginx
    deploy:
      replicas: 0
      labels:
        - traefik.enable=true
        # If you do not use the swarm load balancer, traefik will evict the service from its pool
        # as soon as the service is 0/0. If you do not set that, fallback to dynamic-config.yml file usage.
        - traefik.docker.lbswarm=true
        - traefik.http.routers.nginx.middlewares=ondemand-nginx1@docker
        - traefik.http.routers.nginx.rule=PathPrefix(`/nginx1`)
        - traefik.http.services.nginx.loadbalancer.server.port=80

  nginx1:
    image: nginx
    deploy:
      replicas: 0
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.http.routers.nginx.middlewares=ondemand-nginx2@docker
        - traefik.http.routers.nginx.rule=PathPrefix(`/nginx2`)
        - traefik.http.services.nginx.loadbalancer.server.port=80

```

I was trying to have a _generic middleware_, but I have not the needed data within the middleware.
```go
func (e *Ondemand) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
```

I would need to know the traefik provider and and the traefik router info.



I already tried something too complex to achieve this : 

1. Query Traefik API to get routers and providers info
2. Create a Mux router for each route by a Docker provider
3. Try to match the current request URI against all routers
4. If one match, then I have access to all infos needed to create one middleware for multiple containers
Maybe I'll set up an experimental branch with this implementation.
